#!/usr/bin/env perl

use warnings;
use strict;
use POSIX;

sub usage
{
  die qq{Usage: $0 [filename]\n};
}


if ( scalar @ARGV < 1 ) {
  usage;
}

my $filename = shift;

open GNUPLOT, q{| gnuplot} or die;

print GNUPLOT <<END;
set terminal svg size 1024,560 fixed  fname 'Arial' rounded solid mouse standalone name "Throughput"
set datafile separator ","
set xlabel "time (s)"
set ylabel "queueing delay (ms)"
set ytics nomirror
set y2label "link utilization (percentage)"
set y2tics nomirror
set y2range [0:101]
set style fill solid 0.2 noborder
set output "/dev/stdout"
set key center outside top horizontal
plot '$filename' using 1:3 title "queuing delay" with lines axis x1y1 lw 4, '$filename' using 1:2 with lines title "link utilization" axis x1y2 lw 2
END

close GNUPLOT or die qq{$!};